prefix schema: <http://schema.org/>
prefix : <http://Carnot.org/>

SELECT (?v_1 AS ?name)
       (?v_2 AS ?AssignmentName)
       (?v_3 AS ?PairName)
  	   (?a   AS ?Assignment)
       (?p   AS ?Pair)
WHERE { ?e a :Employee .
?e    schema:name ?v_1 .
?e    :employeeAssignment ?a .
?a    schema:name ?v_2 .
?a    :pairAssignment ?p .
?p    schema:name ?v_3 .
}
